[package]
name = "row-challenge"
version = "0.1.0"
edition = "2024"

[dependencies]
memmap2 = "0.9"
rand = "0.8"
ahash = "0.8"
memchr = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
